"""empty message

Revision ID: e163dad193b5
Revises: 51fd5bd354b0
Create Date: 2024-05-23 20:12:35.794319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e163dad193b5'
down_revision = '51fd5bd354b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asked_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asked_questions', schema=None) as batch_op:
        batch_op.drop_column('quiz_id')

    # ### end Alembic commands ###
